### ISSUE TITLE
Game Crash caused by display modes

### ISSUE THREAD

**Issue by Xukkorz** [agg23/openfpga-wonderswan#6] opened 2024-01-03 02:00 UTC
### Version (or build number)

1.0.0

### Steps to reproduce

Flipping between Display modes causes roms to crash. All Display modes were enabled via Mattpanella's script and in quick flipping between them in games it causes the rom to crash. Seems to mostly crash flipping between Grayscale LCD and subsequent display modes. Core is still responsive and can reload new roms. Seems to happen in WS mode as well as WSC mode.

### Expected Behavior

Display Mode to change rom to not crash

### Actual Behavior

Rom Whites out or crashes on a screen.

**Comment by davewongillies** [comment] 2024-02-07 17:46
I just tested this now with firmware 2.1 (which fixed this problem for other cores) and couldn't reproduce it

**Comment by agg23** [comment] 2024-02-07 17:49
Yes, this should be fixed with 2.1. Thanks for reminding me to close this.

**Closed as completed by agg23** 2024-02-07 17:49 UTC
Labels: bug
